[package]
name = "ch-proto"
version = "0.1.0"
edition = "2021"

[features]
integration = []

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "varint"
harness = false

[[bench]]
name = "hello"
harness = false

[[bench]]
name = "query"
harness = false

[[bench]]
name = "column"
harness = false

[dependencies]
uuid = { version = "1.23.1", features = ["v4"] }
hostname = "0.4"
