services:
  clickhouse:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION-25.3-alpine}
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_SKIP_USER_SETUP: 1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 1s
      timeout: 1s
      retries: 30
